dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- pytest
- pytest --cov=thinkcell
after_success:
- coveralls
deploy:
  provider: pypi
  user: duarteocarmo
  password:
    secure: jT5zWf1pIIKfIdf6jlBSkeEgXWorVPza1pz70fprHezyA6ouby5l22p2YnfdH4AZ7Y64nk9PbcY5M9khocQt/dPRx5ERrYYbQMkljRT/DaOwYWZ/sKeif0AZHKBQ5KYNfbIyFY7h1KB93xYiXoLylpF4bIApmNZZT3P170ujhELc+jG+DJSLUB8jwBK9I2uEY63rHvS7d8w+Lz8lQMOapxfgtCZQDYD8PXk8QAzKtnSRL4kz0XPBfCPiohQzlnyCSYqit59PHUDOP6L24u9b5lTSX1G7CPyCElSw6pjPpibyNSgyFGeoDFEaDLwcRub6Dbu21aKpT7TCwq9Mu/ezK7GXbjp48g1AHd3CCtFkW2qJG1xoAIX+akZxvxt5CUCganF7oM9J1skA5LQON159B6bkb1IdBjuURg6u4BiQAz0WZDcWWbRMBpK8sISfQncThqUprowUljDwFe9zI4QSDWBbYOZ2JzrStH384pm0SFA7f4G4nmzooDJVo2kp2hL3ahW5dR9COc1kAeXgx7ibrX6y56YqeVHSwQQBUVCFhTIg6AA1Qf+PfP5Z7RugKFLdi3SVzCRZMeNXZOSULAADNiuHrKAhU+yGcxLe00w2wVs/jOguCLM2r68/GzQXf3wo7/tu9pr89PMKW57R69Jvm/8r1rcxsjBw1td2BjYlMNQ=
  on:
    tags: true
